# set default permission of file to 644 (rw-r--r--)
umask 022

# Temporary fix for the path order in the login shell.
# $PATH is overriden by path_helper in /etc/zprofile,
# after ~/.zshenv.
path=(
  $path
  /usr/local/{bin,sbin}
)

# Let ~/.local/bin take precedence
if ! (( ${path[(I)$HOME/.local/bin]} )); then
  path=( $HOME/.local/bin $path )
fi
